/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author undine
 */
import java.awt.GridLayout;
import java.util.*;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

public class vistaCajero extends javax.swing.JFrame {
    
    GregorianCalendar getFecha = new GregorianCalendar();
    ArrayList<tarjeta> tarjetas = new ArrayList<tarjeta>();
    ArrayList<cuentaTransaccion> transacciones = new ArrayList<cuentaTransaccion>();
    ArrayList<cuenta> cuentas = new ArrayList<cuenta>();
    ArrayList<tipoCuenta> tiposCuenta = new ArrayList<tipoCuenta>();
    ArrayList<transaccion> tiposTransaccion = new ArrayList<>();
    String[] columnaTransaccion = {"","","","",""};
    int numTarjeta = 0;
    int tipoTarjeta = 0;
    int tipoTransaccion = 0;
    int idFranquicia = 0;
    int valorRetiro = 0;
    int valorDeposito = 0;
    int numTransaccion = 0;
    int cuentaTransferencia = 0;
    /**
     * Creates new form vistaCajero
     */
    
    public vistaCajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ahorrosCorriente = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        formTransacciones = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        formValor = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        digiteClave = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton12 = new javax.swing.JButton();
        claveInvalida = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        fondosInsuficientes = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        reporteTransaccion = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        cuentaDestino = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        ahorrosCorriente.setBounds(new java.awt.Rectangle(0, 0, 460, 460));

        jButton3.setText("Ahorros");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Corriente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton10.setText("Salir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ahorrosCorrienteLayout = new javax.swing.GroupLayout(ahorrosCorriente.getContentPane());
        ahorrosCorriente.getContentPane().setLayout(ahorrosCorrienteLayout);
        ahorrosCorrienteLayout.setHorizontalGroup(
            ahorrosCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ahorrosCorrienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ahorrosCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ahorrosCorrienteLayout.setVerticalGroup(
            ahorrosCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ahorrosCorrienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton5.setText("Retiro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Consulta De Saldo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Consignación");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Transferencia");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Consulta De Movimientos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formTransaccionesLayout = new javax.swing.GroupLayout(formTransacciones.getContentPane());
        formTransacciones.getContentPane().setLayout(formTransaccionesLayout);
        formTransaccionesLayout.setHorizontalGroup(
            formTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTransaccionesLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(formTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        formTransaccionesLayout.setVerticalGroup(
            formTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTransaccionesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Digite El Valor");

        jButton11.setText("Continuar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formValorLayout = new javax.swing.GroupLayout(formValor.getContentPane());
        formValor.getContentPane().setLayout(formValorLayout);
        formValorLayout.setHorizontalGroup(
            formValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formValorLayout.createSequentialGroup()
                .addGroup(formValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formValorLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel2))
                    .addGroup(formValorLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formValorLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        formValorLayout.setVerticalGroup(
            formValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formValorLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Digite Su Clave");

        jButton12.setText("Continuar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout digiteClaveLayout = new javax.swing.GroupLayout(digiteClave.getContentPane());
        digiteClave.getContentPane().setLayout(digiteClaveLayout);
        digiteClaveLayout.setHorizontalGroup(
            digiteClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digiteClaveLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(digiteClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(digiteClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(digiteClaveLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        digiteClaveLayout.setVerticalGroup(
            digiteClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digiteClaveLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Su Clave Es Invalida!!");

        jButton13.setText("Continuar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout claveInvalidaLayout = new javax.swing.GroupLayout(claveInvalida.getContentPane());
        claveInvalida.getContentPane().setLayout(claveInvalidaLayout);
        claveInvalidaLayout.setHorizontalGroup(
            claveInvalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(claveInvalidaLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(claveInvalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, claveInvalidaLayout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        claveInvalidaLayout.setVerticalGroup(
            claveInvalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(claveInvalidaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Fondos Insuficientes!!");

        jButton14.setText("jButton14");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondosInsuficientesLayout = new javax.swing.GroupLayout(fondosInsuficientes.getContentPane());
        fondosInsuficientes.getContentPane().setLayout(fondosInsuficientesLayout);
        fondosInsuficientesLayout.setHorizontalGroup(
            fondosInsuficientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondosInsuficientesLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(fondosInsuficientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondosInsuficientesLayout.createSequentialGroup()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGap(110, 110, 110))
        );
        fondosInsuficientesLayout.setVerticalGroup(
            fondosInsuficientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondosInsuficientesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Transaccion Exitosa");

        jButton15.setText("Salir");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reporteTransaccionLayout = new javax.swing.GroupLayout(reporteTransaccion.getContentPane());
        reporteTransaccion.getContentPane().setLayout(reporteTransaccionLayout);
        reporteTransaccionLayout.setHorizontalGroup(
            reporteTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteTransaccionLayout.createSequentialGroup()
                .addGroup(reporteTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reporteTransaccionLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reporteTransaccionLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel6))
                    .addGroup(reporteTransaccionLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        reporteTransaccionLayout.setVerticalGroup(
            reporteTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteTransaccionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Cuenta de destino");

        jButton16.setText("Continuar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuentaDestinoLayout = new javax.swing.GroupLayout(cuentaDestino.getContentPane());
        cuentaDestino.getContentPane().setLayout(cuentaDestinoLayout);
        cuentaDestinoLayout.setHorizontalGroup(
            cuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentaDestinoLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(cuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        cuentaDestinoLayout.setVerticalGroup(
            cuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentaDestinoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 460, 460));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido Por Favor Inserte Su Tarjeta");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton1)
                        .addGap(86, 86, 86)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(numTransaccion == 0){
            tiposTransaccion.add(new transaccion(1, "Retiro"));
            tiposTransaccion.add(new transaccion(2, "Consulta De Saldo"));
            tiposTransaccion.add(new transaccion(3, "Consignación"));
            tiposTransaccion.add(new transaccion(4, "Transferencia"));
            tiposTransaccion.add(new transaccion(5, "Movimientos"));
        
            tiposCuenta.add(new tipoCuenta(1, "Ahorros"));
            tiposCuenta.add(new tipoCuenta(2, "Corriente"));
        
            tarjetas.add(new tarjeta(1, "Visa"));
            tarjetas.add(new tarjeta(1, "Mastercard"));
            tarjetas.add(new tarjeta(1, "Maestro"));
        
            cuentas.add(new cuenta(1, 1, 1, 500000, 1234));
            cuentas.add(new cuenta(2, 1, 2, 1500000, 1234));
            cuentas.add(new cuenta(3, 2, 3, 5200000, 1234));
            cuentas.add(new cuenta(4, 2, 1, 50000, 1234));
        }
        
        numTarjeta = Integer.parseInt(jTextField1.getText());
        numTransaccion++;
        
        ahorrosCorriente.setVisible(true);
        ahorrosCorriente.setBounds(0, 0, 460, 430);
        /*jFrame1.setLayout(new GridLayout(2,1));
        jFrame1.add(new JButton("Ahorros"));
        jFrame1.add(new JButton("Corriente"));*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tipoTarjeta = 1;
        ahorrosCorriente.setVisible(false);
        formTransacciones.setVisible(true);
        formTransacciones.setBounds(0, 0, 460, 430);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tipoTarjeta = 2;
        ahorrosCorriente.setVisible(false);
        formTransacciones.setVisible(true);
        formTransacciones.setBounds(0, 0, 460, 430);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        tipoTransaccion = 1;
        formTransacciones.setVisible(false);
        formValor.setVisible(true);
        formValor.setBounds(0, 0, 460, 430);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        tipoTransaccion = 2;
        formTransacciones.setVisible(false);
        valorRetiro = 0;
        digiteClave.setVisible(true);
        digiteClave.setBounds(0, 0, 460, 430);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        tipoTransaccion = 3;
        formTransacciones.setVisible(false);
        formValor.setVisible(true);
        formValor.setBounds(0, 0, 460, 430);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        tipoTransaccion = 4;
        formTransacciones.setVisible(false);
        formValor.setVisible(true);
        formValor.setBounds(0, 0, 460, 430);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        tipoTransaccion = 5;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        ahorrosCorriente.setVisible(false);
        jTextField1.setText(null);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        valorRetiro = Integer.parseInt(jTextField2.getText());
        formValor.setVisible(false);
        
        if(tipoTransaccion == 4){
            cuentaDestino.setVisible(true);
            cuentaDestino.setBounds(0, 0, 460, 430);
        }else{
            digiteClave.setVisible(true);
            digiteClave.setBounds(0, 0, 460, 430);
        }   
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        char[] clave = jPasswordField1.getPassword();//Vector de caracteres con el pass
        String cadena = "";
        int parseado = 0,j = 0,nuevoSaldo = 0;
        //Ciclo para unir el pass y luego parsearlo a int
        for(int i=0; i<clave.length;i++){
            cadena = cadena + clave[i];
            //System.out.println(cadena);
        }
        parseado = Integer.parseInt(cadena);
        
        System.out.println(parseado);
        
        for(j=0;j<cuentas.size();j++){
            if(cuentas.get(j).getClave() == parseado && cuentas.get(j).getIdCuenta() == numTarjeta){
                switch(tipoTransaccion){
                    case 1:{
                        if(cuentas.get(j).getSaldo()>valorRetiro){
                            nuevoSaldo = cuentas.get(j).getSaldo() - valorRetiro;
                            cuentas.get(j).setSaldo(nuevoSaldo);
                            System.out.println(cuentas.get(j).getSaldo());
                            transacciones.add(new cuentaTransaccion(tipoTransaccion, numTarjeta, numTransaccion, nuevoSaldo));
                            j = cuentas.size();
                            digiteClave.setVisible(false);
                            reporteTransaccion.setBounds(0, 0, 460, 430);
                            reporteTransaccion.setVisible(true);
                            cadena = generarRecibo(valorRetiro,nuevoSaldo,numTarjeta,numTransaccion);
                            jTextArea1.setText(cadena);
                        }else{
                            //Saldo insuficiente
                            digiteClave.setVisible(false);
                            fondosInsuficientes.setBounds(0, 0, 460, 430);
                            fondosInsuficientes.setVisible(true);
                            j = cuentas.size();
                        }
                        break;
                    }
                    case 2:{
                        if(cuentas.get(j).getSaldo()>valorRetiro){
                            nuevoSaldo = cuentas.get(j).getSaldo() - valorRetiro;
                            cuentas.get(j).setSaldo(nuevoSaldo);
                            System.out.println(cuentas.get(j).getSaldo());
                            transacciones.add(new cuentaTransaccion(tipoTransaccion, numTarjeta, numTransaccion, nuevoSaldo));
                            j = cuentas.size();
                            digiteClave.setVisible(false);
                            reporteTransaccion.setBounds(0, 0, 460, 430);
                            reporteTransaccion.setVisible(true);
                            cadena = generarRecibo(valorRetiro,nuevoSaldo,numTarjeta,numTransaccion);
                            jTextArea1.setText(cadena);
                        }
                        break;
                    }
                    case 3:{
                        nuevoSaldo = cuentas.get(j).getSaldo() + valorRetiro;
                        cuentas.get(j).setSaldo(nuevoSaldo);
                        System.out.println(cuentas.get(j).getSaldo());
                        transacciones.add(new cuentaTransaccion(tipoTransaccion, numTarjeta, numTransaccion, nuevoSaldo));
                        j = cuentas.size();
                        digiteClave.setVisible(false);
                        reporteTransaccion.setBounds(0, 0, 460, 430);
                        reporteTransaccion.setVisible(true);
                        cadena = generarRecibo(valorRetiro,nuevoSaldo,numTarjeta,numTransaccion);
                        jTextArea1.setText(cadena);
                        break;
                    }
                    case 4:{
                        if(cuentas.get(j).getSaldo()>valorRetiro){
                            for(int k = 0; k < cuentas.size(); k++){
                                if(cuentas.get(k).idTarjeta == cuentaTransferencia){
                                    nuevoSaldo = cuentas.get(j).getSaldo() - valorRetiro;
                                    cuentas.get(j).setSaldo(nuevoSaldo);
                                    System.out.println(cuentas.get(j).getSaldo());
                                    transacciones.add(new cuentaTransaccion(tipoTransaccion, numTarjeta, numTransaccion, nuevoSaldo));
                                    j = cuentas.size();
                                    cadena = generarRecibo(valorRetiro,nuevoSaldo,numTarjeta,numTransaccion);
                                    jTextArea1.setText(cadena);
                                    numTransaccion++;
                                    
                                    nuevoSaldo = cuentas.get(k).getSaldo() + valorRetiro;
                                    cuentas.get(k).setSaldo(nuevoSaldo);
                                    System.out.println(cuentas.get(k).getSaldo());
                                    transacciones.add(new cuentaTransaccion(tipoTransaccion, cuentaTransferencia, numTransaccion, nuevoSaldo));
                                    
                                    digiteClave.setVisible(false);
                                    reporteTransaccion.setBounds(0, 0, 460, 430);
                                    reporteTransaccion.setVisible(true);                                   
                                }else{
                                    
                                }
                            }
                        }else{
                            //Saldo insuficiente
                            digiteClave.setVisible(false);
                            fondosInsuficientes.setBounds(0, 0, 460, 430);
                            fondosInsuficientes.setVisible(true);
                            j = cuentas.size();
                        }
                        break;
                    }
                    case 5:{
                        
                    }
                }
            }else{
                //Clave invalida
                digiteClave.setVisible(false);
                claveInvalida.setBounds(0, 0, 460, 430);
                claveInvalida.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        claveInvalida.setVisible(false);
        jTextField1.setText(null);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        fondosInsuficientes.setVisible(false);
        jTextField1.setText(null);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        reporteTransaccion.setVisible(false);
        jTextField1.setText(null);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        cuentaTransferencia = Integer.parseInt(jTextField3.getText());
        cuentaDestino.setVisible(false);
        digiteClave.setVisible(true);
        digiteClave.setBounds(0, 0, 460, 430);
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ahorrosCorriente;
    private javax.swing.JFrame claveInvalida;
    private javax.swing.JFrame cuentaDestino;
    private javax.swing.JFrame digiteClave;
    private javax.swing.JFrame fondosInsuficientes;
    private javax.swing.JFrame formTransacciones;
    private javax.swing.JFrame formValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JFrame reporteTransaccion;
    // End of variables declaration//GEN-END:variables

    String generarRecibo(int valorTransaccion, int nuevoSaldo, int numTarjeta,int numTransaccion ){
        String cadena = "";
        GregorianCalendar getFecha = new GregorianCalendar();
        GregorianCalendar getHora = new GregorianCalendar();
        
        cadena = "Fecha: " + getFecha.get(Calendar.DATE) + "/" + getFecha.get(Calendar.MONTH) + "/" + getFecha.get(Calendar.YEAR) + "\n";
        cadena = cadena + "Hora: " + getFecha.get(Calendar.HOUR) + ":" + getFecha.get(Calendar.MINUTE) + ":" + getFecha.get(Calendar.SECOND) + "\n";
        cadena = cadena + "Numero de transaccion: " + numTransaccion + "\n" + "Numero de cuenta: " + numTarjeta + "\n" + "Valor de la transaccion: " + valorTransaccion + "\n" + "Nuevo saldo: " + nuevoSaldo;
        return cadena;
    }
}